apiVersion: v1
entries:
  azure-service-operator:
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2020-05-26T16:33:55.587588-07:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: 8690a8f38184b7630c4951bdf93fd30a44d9dd3d82be912e2f4e5c9aa05fdd8a
    home: https://github.com/Azure/azure-service-operator
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator
    urls:
    - azure-service-operator-0.1.0.tgz
    version: 0.1.0
generated: "2020-05-26T16:33:55.58204-07:00"
